### ISSUE TITLE
sysvinit stop action failed on Centos 6

### ISSUE THREAD

**Issue by kakawait** [silpion/ansible-tomcat#7] opened 2015-05-19 16:55 UTC
Fresh installation on Centos 6 (using vagrant https://atlas.hashicorp.com/hansode/boxes/centos-6.6-x86_64)

```
[vagrant@vagrant-centos6 ~]$ sudo /etc/init.d/tomcat stop
Stopping tomcat:                                           [FAILED]
```

I have to kill it manually using `kill -9 {pid}`.

`start` action works great.

cause:

`killproc` does not work correctly

```
[vagrant@vagrant-centos6 ~]$ . /etc/init.d/functions 
[vagrant@vagrant-centos6 ~]$ killproc tomcat
[vagrant@vagrant-centos6 ~]$                               [FAILED]
```

**Comment by kakawait** [comment] 2015-05-20 08:34
Fix (waiting for pull request I have to install your integration system):

add following export `export CATALINA_PID=/var/run/tomcat.pid` fixes `killproc` for centos 6

**Comment by spul** [comment] 2015-05-20 08:47
Right, I'm aware of that but didn't find time to fix this. [0.6.0](https://github.com/silpion/ansible-tomcat/tree/0.6.0) introduced a feature from [trumant](https://github.com/trumant) which allows to override the templates for various init systems, which I believe was intended to fix this.
I'll have a look once tomcat8 support is done.

**Comment by spul** [comment] 2015-05-20 11:27
Fixed now in internal feature, assigned PR to team. Once PR is done, fixes will get released.

**Comment by spul** [comment] 2015-06-11 10:30
Fixed with current release.

**Closed by spul** 2015-06-11 10:30 UTC
